const C = {
    ADD_AMOUNT: "ADD_AMOUNT",
    REMOVE_AMOUNT: "REMOVE_AMOUNT",
    CHOOSE_PRODUCT:"CHOOSE_PRODUCT",
    CALC_AMOUNT:"CALC_AMOUNT",
    CHOOSE_UNIT:'CHOOSE_UNIT',
    GET_UNITS_FOR_URL:"GET_UNITS_FOR_URL"
};

export default C;